// Picks the "one thing to try next month" line at the foot of the client report.
//
// Rule-based on purpose, not generated by a model: this goes to a real customer
// under Jay's name, so every sentence has to be true of THAT client's month and
// has to read the same in the preview as in the sent email. A rule catalogue
// gives specificity ("47 people looked, nobody rang") that a generic line can't,
// with no API key, no per-send cost, and nothing to fact-check.
//
// Two safeguards worth keeping:
//  - Nothing here promises a result or criticises the client.
//  - If the site tracking isn't live yet the month reads as all-zeros, which is
//    OUR setup gap, not a fact about their business. In that case only the
//    evergreen tips are eligible, so the report can never tell a client their
//    traffic collapsed when the truth is we haven't installed the script.

import type { ReportSnapshot } from "@/lib/reportTemplate";

export interface GrowthTip {
  title: string;
  body: string;
}

// Stable per-period index. Same tip in the preview and the sent email, a
// different one next month — and no Math.random(), which would make the
// preview lie about what the client is going to receive.
function periodSeed(period: string): number {
  let h = 0;
  for (let i = 0; i < period.length; i++) h = (h * 31 + period.charCodeAt(i)) >>> 0;
  return h;
}

// True when we have real traffic data for either this month or last. All-zero
// months usually mean the tracking script isn't on the site yet.
function hasTrafficData(s: ReportSnapshot): boolean {
  return s.site.page_views > 0 || s.site.prev_page_views > 0;
}

interface Rule {
  id: string;
  when: (s: ReportSnapshot) => boolean;
  tip: (s: ReportSnapshot) => GrowthTip;
}

// Situational tips — only offered when the month's numbers actually support them.
const RULES: Rule[] = [
  {
    // Plenty of interest, nobody got in touch.
    id: "traffic-no-enquiries",
    when: (s) => s.site.page_views >= 30 && s.leads.total === 0,
    tip: (s) => ({
      title: "Turning visitors into calls",
      body: `${s.site.page_views} page views this month, but nobody got in touch. That usually means people are checking you out and then going elsewhere to make the decision. Fresh photos of recent jobs and a few more reviews tend to be what tips someone into picking up the phone — send any job pictures over and we'll get them on the site.`,
    }),
  },
  {
    // Ringing but not filling the form in.
    id: "calls-not-forms",
    when: (s) => s.site.calls > 0 && s.site.forms === 0,
    tip: () => ({
      title: "Your customers would rather ring",
      body: `Every enquiry this month came by phone rather than the contact form. That's completely normal for trade work — people want a quick answer. It's worth making sure someone can pick up during the day, or that missed calls get a text back the same hour, because most people simply ring the next company on the list.`,
    }),
  },
  {
    // Good month — reinforce it.
    id: "enquiries-up",
    when: (s) => s.leads.total > 0 && s.leads.prev_total > 0 && s.leads.total > s.leads.prev_total,
    tip: (s) => ({
      title: "Keep the momentum going",
      body: `Enquiries went up from ${s.leads.prev_total} to ${s.leads.total} this month. The single best thing you can do off the back of a good month is ask each of those customers for a Google review once the job's done — it compounds, and it's what pushes you up the local results for next month.`,
    }),
  },
  {
    // Quieter month — explain it without alarming them.
    id: "enquiries-down",
    when: (s) => s.leads.prev_total > 0 && s.leads.total < s.leads.prev_total,
    tip: () => ({
      title: "A quieter month",
      body: `Enquiries were down on last month. Trade work swings around with the weather and the time of year, so one quieter month on its own isn't a worry. If you want to bring work forward, posting a couple of recent jobs on your Facebook page and sending the link to past customers is the quickest way to shake something loose.`,
    }),
  },
  {
    // Traffic climbing, enquiries flat.
    id: "traffic-up-enquiries-flat",
    when: (s) =>
      s.site.page_views > s.site.prev_page_views &&
      s.site.prev_page_views > 0 &&
      s.leads.total <= s.leads.prev_total,
    tip: () => ({
      title: "More people looking",
      body: `More people found the site this month than last, even though enquiries held steady. That's the harder half of the job already working. The next step is giving them a reason to choose you over the other tab they've got open — recent photos and reviews do more of that than anything else.`,
    }),
  },
  {
    // Room to improve on search.
    id: "seo-room",
    when: (s) => s.seo.score !== null && s.seo.score < 7,
    tip: () => ({
      title: "Getting found for more searches",
      body: `There's still headroom in how the site ranks for local searches, and that's on us — we'll keep working through it. What helps most from your end is telling us the jobs you actually want more of, and the towns you're happy to travel to, so we're targeting the searches worth winning rather than all of them.`,
    }),
  },
  {
    // Strong SEO — shift the focus.
    id: "seo-strong",
    when: (s) => s.seo.score !== null && s.seo.score >= 8,
    tip: () => ({
      title: "You're well placed on search",
      body: `The site's in good shape for local searches. At this point the thing that moves the needle most isn't the website, it's your Google reviews — they're what someone compares when two firms both look decent. Asking every happy customer on the day you finish is the habit that pays.`,
    }),
  },
  {
    // Everything riding on one channel.
    id: "single-source",
    when: (s) =>
      s.leads.total >= 3 &&
      s.leads.by_source.length > 0 &&
      s.leads.by_source[0].count / s.leads.total >= 0.8,
    tip: (s) => ({
      title: "Spreading where work comes from",
      body: `Most of this month's enquiries came through one route (${s.leads.by_source[0].source}). That's fine while it's working, but it's worth having a second one ticking over so a quiet spell in one place doesn't empty the diary. Google reviews and a monthly post of recent work are the two lowest-effort options.`,
    }),
  },
];

// Always-true advice, used when the month's data can't support a specific
// observation. Nothing here makes a claim about their numbers.
const EVERGREEN: GrowthTip[] = [
  {
    title: "Ask for the review on the day",
    body: `Google reviews are the strongest thing you can influence for local work — they lift where you show up in the results and they're what people read before ringing. The trick is asking on the day you finish, while they're still pleased with the job. A week later and most people never get round to it.`,
  },
  {
    title: "Send us your job photos",
    body: `Before-and-after photos of recent work are the single best thing you can send over. People choosing a tradesman are looking for proof you've done their job before, on a house like theirs. Even quick phone snaps work — send them across whenever you have them and we'll get them onto the site.`,
  },
  {
    title: "Be the one who answers",
    body: `Most people ringing round for a quote go with whoever gets back to them first, not whoever's cheapest. If you can't take a call on site, a quick text back the same hour keeps you in the running. It's the cheapest advantage there is in this trade.`,
  },
  {
    title: "Tell us the work you want more of",
    body: `If there's a particular job you'd rather be doing — the bigger installs, or a specific area you'd like more of — let us know. We can weight the site towards those searches, so more of what comes in is work you actually want to quote for.`,
  },
  {
    title: "Keep your Google listing current",
    body: `Your Google Business Profile does a lot of quiet work — it's what shows in the map results before anyone reaches the website. Keeping the opening hours right and adding a photo every month or so is a small habit that keeps you visible locally.`,
  },
];

/**
 * The tip for this client's month. Situational rules win when the data supports
 * them; among equally-valid rules the period decides, so the tip changes month
 * to month instead of repeating while a situation persists.
 */
export function pickGrowthTip(s: ReportSnapshot): GrowthTip {
  const seed = periodSeed(s.period);

  if (hasTrafficData(s)) {
    const matched = RULES.filter((r) => r.when(s));
    if (matched.length > 0) return matched[seed % matched.length].tip(s);
  }

  return EVERGREEN[seed % EVERGREEN.length];
}
